language: C
install: make cmake
compiler:
 - gcc
script:
 - cmake -DSANITIZE_ADDRESS=On -DSANITIZE_UNDEFINED=On -DCMAKE_BUILD_TYPE=Debug .
 - make
 - make test
 - sh verify_with_test_data.sh

after_success:
 - bash <(curl -s https://codecov.io/bash)
